#!/usr/bin/php-cli

<?php
// Variables
$dbip = "localhost";
$dbport = "3306";
$rootusername = "root";
$rootpassword = "rootpasss";

$whm_plan = "wordpress_auto";

// ----------------------------------------

// Required to fix print
echo '<br />'; 

// Setup opts array
$opts = array();
$argv0 = array_shift($argv);
while(count($argv)) {
	$key = array_shift($argv);
	$value = array_shift($argv);
	$opts[$key] = $value;
}

if ($opts['plan'] == $whm_plan){
	// Setup user
	$cpuser = $opts['user'];
	$dbuser = substr($cpuser, 0, 8) . '_usr';
	$dbpass = createPassword(8);
	
	// Create the database
	$con = mysql_connect($dbip,$rootusername,$rootpassword);
	$dbname = getDatabaseName($con, substr($cpuser, 0, 8) . '_wpdb');
	mysql_query("CREATE DATABASE {$dbname}",$con)or die(mysql_error());
	echo 'database created... <br />';
	mysql_query("CREATE USER '{$dbuser}'@'{$dbip}' IDENTIFIED BY '{$dbpass}'",$con) or die(mysql_error());
	echo 'user created... <br />';
	mysql_query("GRANT ALL ON {$dbname}.* to '{$dbuser}'@'{$dbip}'",$con) or die(mysql_error());
	echo 'all granted... <br />';	
	mysql_query("GRANT DROP ON {$dbname}.* to '{$dbuser}'@'{$dbip}'",$con) or die(mysql_error());
	echo 'drop granted... <br />';	 

	shell_exec("/usr/local/cpanel/bin/dbmaptool {$cpuser} --type mysql --dbs '{$dbname}' --dbusers '{$dbuser}'");
	echo 'db mapped... <br />';

	// Change our working directory
	chdir("/home/{$opts['user']}/public_html");
	
	// Remove CGI Bin folder
	shell_exec('rm -rf cgi-bin');
	
	// Download and extract the latest version of Wordpress	
	shell_exec('wget http://wordpress.org/latest.zip');
	shell_exec('unzip latest.zip');
	
	// Extract files, move up a directory, and remove our wordpress folder
	chdir("/home/{$opts['user']}/public_html/wordpress");
	shell_exec('mv * ../');
	chdir("/home/{$opts['user']}/public_html");
	shell_exec('rm -rf wordpress');
	echo 'files unzipped... <br />';
	// Create a configuration file based off of the sample
	$content = file_get_contents('wp-config-sample.php');
	
	// Replace the default values in the sample with our custom
	$content = str_replace('database_name_here', $dbname, $content);	
	$content = str_replace('username_here', $dbuser, $content);
	$content = str_replace('password_here', $dbpass, $content);
	$content = str_replace('localhost', $dbip, $content);
	
	// Create file
	$handle = fopen('wp-config.php', 'x+');
	fwrite($handle, $content);
	fclose($handle);
	echo 'config edited... <br />';

	// Update permissions
	shell_exec("chown -R {$opts['user']} .");
	shell_exec("chgrp -R {$opts['user']} .");
	shell_exec('chgrp nobody .');
	echo 'access rights changed... <br />';

	// Display our info to the user
	echo 'Wordpress Install...Done<br />';
	echo 'MySQL Pass:'.$dbpass.'<br />';
}

function createPassword($length) {
	$chars = "234567890abcdefghijkmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
	$i = 0;
	$password = "";
	while ($i <= $length) {
		$password .= $chars{mt_rand(0,strlen($chars))};
		$i++;
	}
	return $password;
}

function getDatabaseName($con,$dbname){
	if (!mysql_select_db($dbname)){
		return $dbname;
	}
	else {
		getDatabaseName($con,$dbname.'n');
	}
}

?>
